In [1]:
import tensorflow as tf

## Tensor 기본 명령어

In [2]:
t0 = tf.constant(1) 
print(t0)
print(tf.rank(t0)) # 축의 개수를 반환합니다.

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


2023-07-24 11:29:26.042211: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
t1 = tf.constant([1, 2, 3]) 
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
t1 = tf.constant([[1, 2, 3],[4,5,6],[7,8,9]]) 
print(t1)
print(tf.rank(t1))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# Q. 위 이미지와 같은 크기(3, 3, 3)의 3차원 텐서를 만들고, 차원을 반환해 주세요.
t1 = tf.constant([[[1, 2, 3],[4,5,6],[7,8,9]],[[1, 2, 3],[4,5,6],[7,8,9]],[[1, 2, 3],[4,5,6],[7,8,9]]]) 
print(t1)
print(tf.rank(t1))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


## Tensor의 shape

In [2]:
# Tensor의 shape 변환

x = tf.constant([[1], [2], [3]])
print(x)
print(x.shape)

y = tf.reshape(x, [1, 3])
# Tensor x를 [1,3] 으로 변경
# 3x1 => 1x3으로
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


2023-07-24 23:58:26.867945: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
print(y)
#[[1,2,3]]
print(tf.transpose(y))
# [[1]
#  [2]
#  [3]]

# transpose하면서 reshape이 자연스럽게 일어남
# 1x3 => 3x1
print(y.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(1, 3)


In [4]:
print(x)
print(tf.squeeze(x))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [12]:
z = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(z)

print(tf.squeeze(z))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [13]:
# 차원 추가

print(y)
print(tf.expand_dims(y, axis=0))
print(tf.expand_dims(y, axis=1))
print(tf.expand_dims(y, axis=2))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


In [14]:
# 텐서 분리

print(x)
print(tf.split(x, 3))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
[<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[3]], dtype=int32)>]


In [16]:
z = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(tf.split(z, 3))

[<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>, <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 8, 9]], dtype=int32)>]


In [15]:
# 텐서 연결
# axis로 축 지정

print(x)
print(tf.concat([x, x], axis=0))
print(tf.concat([x, x], axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


## Tensor 연산

In [17]:
print(tf.constant(2) + tf.constant(2))
print(tf.constant(2) - tf.constant(2))
print(tf.add(tf.constant(2), tf.constant(2)))
print(tf.subtract(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [18]:
print(tf.constant(2) * tf.constant(2))
print(tf.constant(2) / tf.constant(2))
print(tf.multiply(tf.constant(2), tf.constant(2)))
print(tf.divide(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)


In [19]:
# 타입을 맞춰준 뒤 연산
print(tf.cast(tf.constant(2), tf.float32) + tf.constant(2.2))

tf.Tensor(4.2, shape=(), dtype=float32)


### 1차원 이상의 Tensor 연산

In [20]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [22]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[4,5],[6,7]])

print(a.shape)
print(b.shape)

print(a + b) # element-wise addition
print(a - b) # element-wise subtraction
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication
print(a / b) # element-wise division

# print(tf.add(a, b))
# print(tf.subtract(a, b))
# print(tf.multiply(a, b))
# print(tf.matmul(a, b))
# print(tf.divide(a, b))

(2, 2)
(2, 2)
tf.Tensor(
[[ 5  7]
 [ 9 11]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-3 -3]
 [-3 -3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 4 10]
 [18 28]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[16 19]
 [36 43]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.25       0.4       ]
 [0.5        0.57142857]], shape=(2, 2), dtype=float64)


In [23]:
c = tf.constant([[4.0, 5.0, 6.0], 
                 [10.0, 9.0, 8.0]])

print(tf.reduce_max(c))
# 최대값 반환
print(tf.argmax(c))
# 최대값의 위치를 반환
print(tf.nn.softmax(c))
# softmax 취하기

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.66524094 0.24472848 0.09003057]], shape=(2, 3), dtype=float32)


In [34]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8]) 
b = tf.constant([[1., 2., 3., 4., 5., 6., 7., 8.]])

# Q. 위에 있는 2개의 텐서를 행렬곱연산이 가능하도록 3차원 텐서로 변환해주세요.
a = tf.reshape(a,[3,1])
print(a.shape)
print(b.shape)
#tf.cast(b,tf.int32)

#print(a@b)

InvalidArgumentError: Input to reshape is a tensor with 8 values, but the requested shape has 3 [Op:Reshape]